#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Tue Jan 21 10:48:50 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import ExtraWidgets as xw
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((600, 420))
        self.SetTitle("AudioConv")

        self.status_bar = self.CreateStatusBar(1)
        self.status_bar.SetStatusWidths([-1])

        self.panel = wx.Panel(self, wx.ID_ANY)

        app_sizer = wx.BoxSizer(wx.VERTICAL)

        input_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel, wx.ID_ANY, "Input"), wx.VERTICAL)
        app_sizer.Add(input_sizer, 0, wx.ALL | wx.EXPAND, 5)

        v_sizer_0 = wx.BoxSizer(wx.HORIZONTAL)
        input_sizer.Add(v_sizer_0, 1, wx.ALL | wx.EXPAND, 5)

        label_1 = wx.StaticText(input_sizer.GetStaticBox(), wx.ID_ANY, u"音源フォルダ")
        v_sizer_0.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.input_folder_selector = xw.DropableDirPickerCtrl(input_sizer.GetStaticBox(), wx.ID_ANY)
        v_sizer_0.Add(self.input_folder_selector, 1, wx.EXPAND, 0)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.panel, wx.ID_ANY, "Output"), wx.VERTICAL)
        app_sizer.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 5)

        v_sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(v_sizer_3, 0, wx.ALL | wx.EXPAND, 5)

        label_4 = wx.StaticText(sizer_2.GetStaticBox(), wx.ID_ANY, u"出力フォルダ")
        v_sizer_3.Add(label_4, 0, wx.RIGHT, 5)

        self.output_folder_selector = xw.DropableDirPickerCtrl(sizer_2.GetStaticBox(), wx.ID_ANY)
        v_sizer_3.Add(self.output_folder_selector, 1, wx.EXPAND, 0)

        app_sizer.Add((20, 10), 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        app_sizer.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 5)

        v_sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(v_sizer_4, 0, wx.ALL | wx.EXPAND, 5)

        self.sample_button = wx.Button(self.panel, wx.ID_ANY, u"サンプル生成")
        v_sizer_4.Add(self.sample_button, 1, wx.RIGHT, 5)

        self.mp3_button = wx.Button(self.panel, wx.ID_ANY, u"MP3変換")
        self.mp3_button.Hide()
        v_sizer_4.Add(self.mp3_button, 1, 0, 0)

        self.go_button = wx.Button(self.panel, wx.ID_ANY, u"サンプル生成&MP3変換")
        self.go_button.Hide()
        v_sizer_4.Add(self.go_button, 1, wx.RIGHT, 5)

        v_sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(v_sizer_6, 0, wx.ALL | wx.EXPAND, 5)

        self.vlc_button = wx.Button(self.panel, wx.ID_ANY, u"VLCで開く")
        self.vlc_button.Hide()
        v_sizer_6.Add(self.vlc_button, 1, wx.RIGHT, 5)

        v_sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self.panel, wx.ID_ANY, "Log"), wx.HORIZONTAL)
        sizer_3.Add(v_sizer_7, 1, wx.ALL | wx.EXPAND, 5)

        self.log_text = wx.TextCtrl(v_sizer_7.GetStaticBox(), wx.ID_ANY, "", style=wx.TE_READONLY)
        v_sizer_7.Add(self.log_text, 1, wx.EXPAND, 0)

        self.panel.SetSizer(app_sizer)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.my_frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.my_frame)
        self.my_frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    MyApp = MyApp(0)
    MyApp.MainLoop()
